# test pipeline
steps:
  - name: node:10.15.1
    entrypoint: yarn
    args: ["remove", "gdd-components"]
  - name: node:10.15.1
    entrypoint: yarn
    args: ["install"]
  - name: node:10.15.1
    entrypoint: yarn
    args: ["add", "firebase-tools"]
  - name: node:10.15.1
    entrypoint: bash
    args: ["./build.sh", "$_GITHUB_ACCESS_TOKEN"]
  - name: "node:10.15.1"
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy", "--project", "$PROJECT_ID", "--token", "$_TOKEN"]