// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Auth
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

// UI
export const DRAWER_TOGGLE = 'DRAWER_TOGGLE';
export const DRAWER_CLOSE = 'DRAWER_CLOSE';

// Claims
export const CLAIMS_REQUEST = 'CLAIMS_REQUEST';
export const GET_CLAIMS_SUCCESS = 'GET_CLAIMS_SUCCESS';
export const DENY_CLAIM_SUCCESS = 'DENY_CLAIM_SUCCESS';
export const APPROVE_CLAIM_SUCCESS = 'APPROVE_CLAIM_SUCCESS';
export const CREATE_CLAIM_SUCCESS = 'CREATE_CLAIM_SUCCESS';
export const GET_CLAIM_SUCCESS = 'GET_CLAIM_SUCCESS';
export const CLAIMS_ERROR = 'CLAIMS_ERROR';

// Search Nonprofits
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const SEARCH_SELECT = 'SEARCH_SELECT';

// Notification
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
