// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Auth
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

// UI
export const DRAWER_TOGGLE = 'DRAWER_TOGGLE';
export const DRAWER_CLOSE = 'DRAWER_CLOSE';

// Claims
export const CLAIMS_REQUEST = 'CLAIMS_REQUEST';
export const GET_CLAIMS_SUCCESS = 'GET_CLAIMS_SUCCESS';
export const DENY_CLAIM_SUCCESS = 'DENY_CLAIM_SUCCESS';
export const APPROVE_CLAIM_SUCCESS = 'APPROVE_CLAIM_SUCCESS';
export const CREATE_CLAIM_SUCCESS = 'CREATE_CLAIM_SUCCESS';
export const GET_CLAIM_SUCCESS = 'GET_CLAIM_SUCCESS';
export const CLAIMS_ERROR = 'CLAIMS_ERROR';

//Profile
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

// Search
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_NONPROFIT_SUCCESS = 'SEARCH_NONPROFIT_SUCCESS';
export const SEARCH_NONPROFIT_FAIL = 'SEARCH_NONPROFIT_FAIL';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS'
export const SEARCH_USERS_FAIL = 'SEARCH_USERS_FAIL'

// Notification
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

// Editing a Nonprofit/User profile
export const SAVE_NONPROFIT_REQUEST = 'SAVE_NONPROFIT_REQUEST';
export const SAVE_NONPROFIT_SUCCESS = 'SAVE_NONPROFIT_SUCCESS';
export const SAVE_NONPROFIT_FAIL = 'SAVE_NONPROFIT_FAIL';
export const SAVE_USER_REQUEST = 'SAVE_USER_REQUEST';
export const SAVE_USER_SUCCESS = 'SAVE_USER_SUCCESS';
export const SAVE_USER_FAIL = 'SAVE_USER_FAIL';

// List of Banned Nonprofits
export const BANNED_REQUEST = 'BANNED_REQUEST';
export const BANNED_SUCCESS = 'BANNED_SUCCESS';
export const BANNED_FAIL = 'BANNED_FAIL';